version: '3.5'
services:
  mysql:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0.39-linuxarm64
    container_name: mysql8_mini_im
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deploy/sql/user.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:7.2.4-linuxarm64
    container_name: redis_mini_im
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
#
#  etcd:
#    image: quay.io/coreos/etcd:v3.5.13
#    container_name: etcd_mini_im
#    restart: on-failure
#    environment:
#      ETCD_DATA_DIR: /etcd-data
#      ETCD_INITIAL_CLUSTER_STATE: new
#      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster-1
#      ETCDCTL_API: 3
#    ports:
#      - "2379:2379"
#      - "2380:2380"
#    volumes:
#      - etcd_data:/etcd-data
#    networks:
#      - etcd-network

volumes:
  mysql_data:
  redis_data:
  etcd_data:

#networks:
#  etcd-network: